version: '3.8'

services:
  web:
    build: ./src
    command: python app/main.py
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=sqlite:///./sqlite.db
